server:
  port: 8083

#配置文件值注入
person:
  last-name: "张三 \n 换行"
  age: 18
  maps:
    k1: v1
    k2: v2
  boss: true
  lists: [1,2,3]
  birth: 2019/11/13
  dog: {name: zsdog}

#指定激活使用那种环境
spring:
  profiles:
    active: dev


